version: 2

builds:
  - builder: rust
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
    flags:
      - --release
      - --locked

archives:
  - formats: [binary]

changelog:
  use: github-native
