name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/setup-mise
      - run: |
          rustup component add clippy
          rustup component add rustfmt
      - run: |
          cargo fmt --check
      - run: |
          cargo clippy --all-targets --all-features -- -D warnings

  test:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-15-intel
          - target: aarch64-apple-darwin
            os: macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/setup-mise
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}
      - run: |
          cargo test --target ${{ matrix.target }}
